---
apiVersion: v1
kind: Namespace
metadata:
  name: postgre
  labels:
    mesh: k8s-mesh-staging
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgre
  namespace: postgre
data:
  # Configuration values can be set as key-value properties
  POSTGRES_DB: "keycloak"
  POSTGRES_PASSWORD: "password"
  POSTGRES_USER: "keycloak"
  PGDATA: "/var/lib/postgresql/data/db-files/"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
  namespace: postgre
  labels:
    app: postgre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        appmesh.k8s.aws/mesh: k8s-mesh-staging
        appmesh.k8s.aws/virtualNode: postgre
      labels:
        app: postgre
    spec:
      #nodeSelector:
        #type: karpenter
      serviceAccountName: postgre
      containers:
        - name: postgre
          image: postgres:15.6-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - keycloak
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-claim0
              subPath: db-files
          envFrom:
          - configMapRef: 
              name: postgre
      restartPolicy: Always
      volumes:
        - name: postgres-claim0
          persistentVolumeClaim:
            claimName: postgres-claim0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: postgres-claim0
  name: postgres-claim0
  namespace: postgre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgre
  namespace: postgre
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::041292242005:role/k8s-mesh-staging-eks-postgre

---
apiVersion: v1
kind: Service
metadata:
  name: postgre
  namespace: postgre
spec:
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: postgre


---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: postgre
  namespace: postgre
spec:
  podSelector:
    matchLabels:
      app: postgre
  listeners:
    - portMapping:
        port: 5432
        protocol: tcp
  serviceDiscovery:
    #dns:
      #hostname: postgre.postgre.svc.cluster.local
    awsCloudMap:
      serviceName: postgre
      namespaceName: k8s-mesh-staging

# ---
# apiVersion: appmesh.k8s.aws/v1beta2
# kind: VirtualRouter
# metadata:
#   name: postgre
#   namespace: postgre
# spec:
#   listeners:
#     - portMapping:
#         port: 5432
#         protocol: http
#   routes:
#     - name: postgre
#       httpRoute:
#         match:
#           prefix: /
#         action:
#           weightedTargets:
#             - virtualNodeRef:
#                 name: postgre
#               weight: 1

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: postgre
  namespace: postgre
spec:
  #awsName: postgre.postgre.svc.cluster.local
  provider:
    virtualNode:
      virtualNodeRef:
        name: postgre


# ---
# apiVersion: appmesh.k8s.aws/v1beta2
# kind: GatewayRoute
# metadata:
#   name: postgre
#   namespace: postgre
# spec:
#   httpRoute:
#     match:
#       prefix: "/"
#       hostname:
#         exact: postgre.skyscaledev.com
#     action:
#       target:
#         virtualService:
#           virtualServiceRef:
#             name: postgre

